apiVersion: v1
kind: Namespace
metadata:
  name: trends
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trend-config
  namespace: trends
data:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "local"
  AWS_SECRET_ACCESS_KEY: "local"
  QUEUE_NAME: "trends"
  SQS_ENDPOINT: "http://elasticmq:9324"
  DATABASE_URL: "postgres://trends:trends@postgres:5432/trends?sslmode=disable"
  WORKERS: "8"
  TOP_N: "30"